### ISSUE TITLE
It might be blindingly obvious, but...

### ISSUE THREAD

**Issue by 0b1kn00b** [haxetink/tink_http#10]
Where are the query parameters on php?

**Comment by kevinresol** [comment]
@0b1kn00b It is in the uri, the part after the question mark `"?"`. See `incomingRequest.header.uri`
For POST data it is in the body. See `incomingRequest.body`

**Comment by 0b1kn00b** [comment]
It's not turning up in php,  I think the uri and query are separate on my rig,  I'll try and get a pull request in.

**Comment by 0b1kn00b** [comment]
#19 fixes this, as far as I can tell
