### ISSUE TITLE
Why RequestHeader API force us to set http protocol

### ISSUE THREAD

**Issue by mikicho** [haxetink/tink_http#102]
As you can see [here](https://github.com/haxetink/tink_http/blob/master/src/tink/http/Request.hx#L20), `protocol` argument have a default value, but `fields` arguments which follow it, have no default argument what force us to do: 
```haxe
new OutgoingRequestHeader(method, url, HTTP1_1 , []) // redundant protocol argument
```
I wanted to PR to switch the arguments, but wonder if there is a hidden reason for that order (don't break the API...)

**Comment by mikicho** [comment]
I can, but why the method signature isn't like this:
```haxe
public function new(method:Method, url:Url, fields, protocol:Protocol = HTTP1_1)
// or even
public function new(method:Method, url:Url, fields = [], protocol:Protocol = HTTP1_1)
```
And then we can:
```haxe
new OutgoingRequestHeader(method, url, [])
// or
new OutgoingRequestHeader(method, url)
```

**Comment by kevinresol** [comment]
You can write `new OutgoingRequestHeader(method, url , [])`

**Comment by mikicho** [comment]
I pretty sure I tried this, but this is working for me now.
Can you explain why this is working? Haxe knows to 'skip' optional arguments when needed?

**Comment by kevinresol** [comment]
yes

**Comment by mikicho** [comment]
This language never stop to surprise me 0_0
