### ISSUE TITLE
PhpContainer needs an update

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#104]
`Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.`

**Comment by benmerckx** [comment]
This seems to be a PHP ini setting that causes the notice, not necessarily in relation to the code, as we don't use the `$HTTP_RAW_POST_DATA` variable anywhere. Which PHP version is this failing on? Apparently the warning is on by default for PHP 5.6.

**Comment by kevinresol** [comment]
Php 5.6 because I am running the tests with haxe 3.

I suspect it is a warning derived from `file_get_contents('php://input')`

**Comment by benmerckx** [comment]
As far as I can tell reading from `php://input` is the way to go. The issue seems to be the warning comes up every time, even when not using `$HTTP_RAW_POST_DATA` (https://bugs.php.net/bug.php?id=66763)

**Comment by back2dos** [comment]
Seems we're reading from [`php://input`](https://github.com/haxetink/tink_http/blob/bf7b8d40a319eb59a470f029cb2905f5563f473d/src/tink/http/containers/PhpContainer.hx#L120) these days.
