### ISSUE TITLE
compilation cache for php not working because of ...

### ISSUE THREAD

**Issue by postite** [haxetink/tink_http#107]
hello :)
with haxe 4.rc1 we can use compilation cache again :)
but tink_http  won't compile :

    /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github    /403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/clients/PhpClient.hx:44: characters  14-25 : String should be tink.http.HeaderName
    /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/clients/PhpClient.hx:44: characters 14-25 : For function argument 'name'
    /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/clients/PhpClient.hx:48: characters 

The terminal process terminated with exit code: 1

PhpClient.hx:44:

    new HeaderField(
             line.substr(0, index),
            line.substr(index + 2)
            );

"line.substr(0,index) " is not casted to HeaderName for some reason...

**Comment by kevinresol** [comment]
Likely to be same as #89

**Comment by postite** [comment]
yes looks like ... but it only occurs with compilation cache...

**Comment by kevinresol** [comment]
Please apply the same workaround and see if that helps

**Comment by postite** [comment]
this workaround works ok .
https://github.com/haxetink/tink_http/commit/d5c6d9b53b33f017a5750464b7514d4c504d0473

**Comment by postite** [comment]
var headers =  [for(i in 1...rawHeaders.length) {
          var line = rawHeaders[i];
          var index = line.indexOf(': ');
          var name = line.substr(0, index);
           new HeaderField(
            name,
            line.substr(index + 2)
            );
        }];

**Comment by postite** [comment]
if you happen to modify the file  , could you modify also the untyped__php__ of the  files by replacing with their corresponding php.Syntax.code  like i did below ... thx :)

    package tink.http.clients;
    
    import tink.http.Client;
    import tink.http.Response;
    import tink.http.Request;
    import tink.http.Header;
    
    using tink.io.Source;
    using tink.CoreApi;
    using StringTools;
    
    class PhpClient implements ClientObject {
      public function new() {}
      
      public function request(req:OutgoingRequest):Promise<IncomingResponse> {
        return Future.async(function(cb) {
          req.body.all().handle(function(chunk) {
            var options = php.Lib.associativeArrayOfObject({
              http: php.Lib.associativeArrayOfObject({
                // protocol_version: // TODO: req does not define the version?
                header: [for(h in req.header) h.toString()].join('\r\n') + '\r\n',
                method: req.header.method,
                content: chunk.toBytes().getData().toString(),
              }),
            });
            //var context = untyped __call__('stream_context_create', options);
            var context = php.Syntax.code('stream_context_create({0})', options);
            var url:String = req.header.url;
            //var result = @:privateAccess new sys.io.FileInput(untyped __call__('fopen', url, 'rb', false, context));
            var result = @:privateAccess new sys.io.FileInput(php.Global.fopen( url, 'rb', false, context));
            
            var rawHeaders:Array<String> = cast php.Lib.toHaxeArray(php.Syntax.code("$http_response_header"));
            
            // http://php.net/manual/en/reserved.variables.httpresponseheader.php#122362
            // $http_response_header includes all the "history" headers in case of redirected response
            var i = rawHeaders.length;
            while(i-- >= 0) if(rawHeaders[i].startsWith('HTTP/')) break;
            rawHeaders = rawHeaders.slice(i);
            
            // construct the header object
            var head = rawHeaders[0].split(' ');
            var headers =  [for(i in 1...rawHeaders.length) {
              var line = rawHeaders[i];
              var index = line.indexOf(': ');
              var name = line.substr(0, index);
               new HeaderField(
                name,
                line.substr(index + 2)
                );
            }];
            
            var header = new ResponseHeader(Std.parseInt(head[1]), head.slice(2).join(' '),  headers);
            cb(Success(new IncomingResponse(header, result.readAll())));
            
            // var headers:IdealSource = php.Lib.toHaxeArray(untyped __php__("$http_response_header")).join('\r\n') + '\r\n';
            // headers.parse(ResponseHeader.parser()).handle(function(o) switch o {
            //   case Success(parsed):
            //   case Failure(e):
            //     cb(Failure(e));
            // });
          });
        });
      }
    }

**Comment by kevinresol** [comment]
Please summit a PR and remember to retain backward compatibility for haxe 3 :)

**Comment by postite** [comment]
aaaah backward compatibilty ... didn't think about that ... 
okay .. wil make it clean ..

**Comment by kevinresol** [comment]
Done with #108
