### ISSUE TITLE
Casing for header names

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#11]
Header names are case-insensitive [according to the spec](http://stackoverflow.com/a/5259004/3212365). So comparing header name in a case-sensitive way ([like this](https://github.com/back2dos/foxhole/blob/3c045a339f8cb28926747dc60ea7518bb248a5b4/src/foxhole/Web.hx#L130)) may lead to potential mismatch/bug. Especially on node js, headers are by default [converted to lower case](https://github.com/nodejs/node-v0.x-archive/issues/1954) by `http.Server`. 

We need some mechanisms to make sure things are consistent. I propose tink_http convert all header names to lower case when parsing the request, and in `header.byName` we lowercase the input parameter before comparing.

**Comment by back2dos** [comment]
You are right, but that is already happening ;)

For header names, there's a `HeaderName` abstract which does the normalization: https://github.com/haxetink/tink_http/blob/master/src/tink/http/Header.hx#L81

Please confirm that it works for you.

**Comment by kevinresol** [comment]
Very nice. I admit that I didn't write any code to test this out. I was just reading the code of foxhole, and missed the fact that `byName` is using `HeaderName`. Thanks!
