### ISSUE TITLE
[question ]is this library  support  Hashlink? 

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_http#111]
is this library support  Hashlink or hxcpp?

**Comment by tynrare** [comment]
Same question. Trying to build for neko:
```
static function main() {
        //Sys.println("Start listen on 8080");
        var container = new ModnekoContainer(8080);
        container.run(function(req) return Future.sync(('Hello, World!':OutgoingResponse)));
    }
```

but it always fails with
`/home/x/workspace/lib/haxe/tink_io/0,7,1/src/tink/io/Source.hx:11: characters 18-30 : You cannot access the js package while targeting neko (for js.lib.Error)`
or `/home/x/workspace/lib/haxe/tink_core/1,26,0/src/tink/core/Callback.hx:41: characters 7-14 : You cannot access the js package while targeting neko (for js.Node)`

**Comment by benmerckx** [comment]
Could you show us the hxml you're using to build? Also, ModnekoContainer is used to for the mod_neko apache extension. You might find TcpContainer easier to get started with. Which also goes for cpp and hl.

**Comment by kevinresol** [comment]
Perhaps due to the depreciation fix for js.Error

**Comment by tynrare** [comment]
Oh. My fault. I fogot to remove `-lib hxnodejs` when tested on neko. 

```
-cp src
# webhost libs
-lib tink_web
# add template (.tt) support
-lib tink_template

# entry
-main toolset.cli.server.Serve
-neko build/serve-http.n
```

Still, doesn't understand how this has to work. Code 
```haxe
    static function main() {
        Sys.println("Start listen on 8080");
        //var container = new ModnekoContainer(8080);
        ModnekoContainer.inst.run(function(req) return Future.sync(('Hello, World!':OutgoingResponse)));
        while(true){
            Sys.sleep(.5);
        }
    }
```
just prints hello world. Does it support actual connection or something?

**Comment by back2dos** [comment]
> Mod_neko is an Apache *module* for Neko. -- https://nekovm.org/doc/mod_neko/

If you wish to go down this path, you will need Apache and mod_neko. The steps are detailed at the above link. For development purposes, you can use https://nekovm.org/doc/tools/#webserver

Neko is on its way out, so I can't really advise using it. HashLink is kinda meant to replace it, but for the time being, it has poor GC and the libuv bindings are still being worked on, so I can't recommend it for server development.

The two recommended options currently are NodeJS and PHP7.

----

As for the original question, HashLink and CPP are currently not supported. I will look into it once the planned asynchronous IO APIs land in the stdlib.

**Comment by onehundredfeet** [comment]
Would be awesome to get this for hash link.  As of this moment, I'm not really sure if there's a hash link supported HTTP library at the moment.

**Comment by benmerckx** [comment]
> As of this moment, I'm not really sure if there's a hash link supported HTTP library at the moment.

There's weblink: https://github.com/PXshadow/weblink
