### ISSUE TITLE
HTTP/2 Multiplexing

### ISSUE THREAD

**Issue by piboistudios** [haxetink/tink_http#115]
I'm still reading up both specs but I know that I want to write a gRPC library which will require the bidirectional streaming that HTTP/2 facilitates.

About how big of a change would one be looking at to take on such an endeavour? Main things that change are:
- connection doesn't necessarily close after response
- server API should be able to handle frames (and also full Messages composed of frames)

**Comment by back2dos** [comment]
Not sure it is practical to make this a part of tink_http. There are many cases of HTTP containers that work purely on a request/response model, e.g. PHP, AWS Lambda, Java Servlets. The focus of tink_http is to provide a consistent API for HTTP, so that applications (and frameworks like tink_web) written on top of it are highly portable.

**Comment by piboistudios** [comment]
Hm. That's definitely something I hadn't really considered. I'll revisit this when it's more relevant but I just feel like tink_web and tink_http are already very close to being able to support this. You can already stream the request while writing the response if AFAIK (Which I guess is half of half way there)

I'll close this for now as I give it more thought.

**Comment by piboistudios** [comment]
@back2dos hey, I've been looking into this more. 

I'm pretty sure this can already be implemented as is with tink_http, would just have to create some special `Stream` type I guess, sort of like [these Go examples](https://grpc.io/docs/languages/go/basics/#implementing-routeguide)

Also, Google closure-library and grpc-web in Haxe will probably need to happen and also subsequently be adapted to tink_http (client-side, though it's already possible both client and server side I'm pretty sure, the client just needs to stream the body.. from what I can tell it buffers it in JsClient); shouldn't be a problem since they're just ReadableStreams/WritableStreams (for example, it has goog.net.streams.XhrNodeReadableStream), which tink_io wraps.

The result of all of that will probably be something like GRPC client (which will be similar to existing JsClient but.. using Google closure externs, whenever I get around to writing those and tinkifying them) and some tink_web macros or something server side (I guess do special stuff if return type/input parameters are aforementioned `Stream` type)

I plan to try out bidirectional streaming with tink_http/tink_web in a bit. 

I'm pretty sure I'll eventually work my way through all these things. When I do, I will show you how I incorporate tink I guess and you guys can decide if it fits in with tink_http

**Comment by kevinresol** [comment]
Is http2 supported in browser js?

**Comment by piboistudios** [comment]
> Is http2 supported in browser js?



Yes via Google closure-library

**Comment by piboistudios** [comment]
[Link](https://github.com/google/closure-library)

**Comment by piboistudios** [comment]
@back2dos also to your point I don't know if it will work for any container other than node and local container; I actually intend to use this surprisingly via local container (SaaS stuff), but I also don't see why it can't work. It is technically still request-esponse model, just the request and response may be streams.

**Comment by kevinresol** [comment]
> Yes via Google closure-library

any examples?

**Comment by piboistudios** [comment]
> > Yes via Google closure-library
> 
> any examples?

Here's the [XhrNodeReadableStream](https://google.github.io/closure-library/api/goog.net.streams.XhrStreamReader.html) should be browser compatible.

**Comment by kevinresol** [comment]
https://stackoverflow.com/a/32592978/3212365

I am sad that they don't bother take the chance to rename the awkwardly named API: XML?HttpRequest
But even worse is that they try to squeeze new APIs into the class... (use onprogress to get pushed resources?!)

**Comment by piboistudios** [comment]
> https://stackoverflow.com/a/32592978/3212365
> 
> I am sad that they don't bother take the chance to rename the awkwardly named API: XML?HttpRequest
> But even worse is that they try to squeeze new APIs into the class... (use onprogress to get pushed resources?!)

;) That's the JS way. Backwards compatibility trumps all else. Also why JS is such a weird language today

But that's also why I am falling in love with closure-library.

Seems they abstract away most of the weird stuff (and they even write wrappers for the bleeding edge APIs which is nice).

haxe externs for google-closure would be a great birthday gift for me next year. 

But Haxe Tinkerbell wrappers for the Google closure library would complete my existence (until the next shiny new server side tech makes it past Draft stage lol)

**Comment by piboistudios** [comment]
@back2dos @kevinresol circling back on this with additional thoughts:

So http2.connect = http request on node (both establish an HTTP cnx), and then `http2.connect` returns `Http2Stream` and you can do `stream.request` (multiple requests on single stream). 

This would mean when creating a client, you should establish a connection to the URL authority (so that the resultant stream lasts the lifetime of the client).

As such, it would make sense for HTTP2 clients to be disposable. 

Not sure what would be the best approach to this, I'd like it to just be a `tink.core.Disposable` but for HTTP/1 clients it's just a noop (harmless I guess) on `dispose`.

**Comment by piboistudios** [comment]
[Example gRPC echo service in `tink_web`](https://github.com/Brave-Pi/bp_grpc/blob/af5757f68e2ed75a4a7446ef6618f63ecbd2f54a/test/RunTests.hx#L113) (using some ugly extern libs I wrote for fetch and node http2)
