### ISSUE TITLE
Standardize headers?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#13]
On nodejs, multiple header values of the same name will be concatenated by `", "` ([doc](https://nodejs.org/api/http.html#http_message_headers)), while on neko/php I suppose there will be multiple entries of the same header name. I am not sure if it should be standardized by tink_http or just let users handle the difference?

**Comment by back2dos** [comment]
Yeah, it's a mess and I definitely want it to be standardized ;)
