### ISSUE TITLE
fetching content with more than 65536 bytes with cpp

### ISSUE THREAD

**Issue by grepsuzette** [haxetink/tink_http#136]
On `CurlClient` targeting `cpp`,
fetching a uri having more than `65536` (and exactly this limit it seems) **stalls**,
whether online or serving a local file at e.g. `http://127.0.0.1/8000/bigfile.txt`.

However, `lix run travix cpp`  passes with the `TestChunk` 
serving more than 200000 bytes.

I was willing to add a failing test but  can't really figure out how.

Here's an example:
```haxe
using tink.CoreApi;
import tink.http.Client;
import tink.http.Client.fetch;

function main() {
    var uri = "http://127.0.0.1:8000/bigfile.txt";  // more than 0xffff size. In node it works
    fetch(uri, { client: Curl, }) 
        .all()
        .handle( out -> switch out {
            case Success(res): 
                trace(res.body);
            case Failure(e): 
                trace('fail: ${e.code} with ${e.data}');
        });
}
```
This replies with a small content, but will hang out indefinitely otherwise. 
Is it because I'm using `.all()`? I never really figured this out.

**Comment by kevinresol** [comment]
I think cpp was never really a good boy in tink_http because of the wonky support in tink_io and tink_runloop, due to blocking/non-blocking sockets and threading etc. If you wish to have a try in debugging this I suggest start looking at [here](https://github.com/haxetink/tink_io/blob/master/src/tink/io/std/InputSource.hx), or I am afraid you will have to wait until any of us have some time to get into this... 😶‍🌫️

**Comment by grepsuzette** [comment]
Oh gosh it seems to be Haxe `sys.io.Process`:
```haxe
     var p = new sys.io.Process("curl", ["http://127.0.0.1:8000/2bytes"]);
      var code = p.exitCode(true);
      trace("exit code: " + code);
      trace(p.stdout.readAll().length);
      p.close();
```
works, but:
```
     var p = new sys.io.Process("curl", ["http://127.0.0.1:8000/100000bytes"]);
      var code = p.exitCode(true);
      trace("exit code: " + code);
      trace(p.stdout.readAll().length);
      p.close();
```
Above fails.

**Comment by grepsuzette** [comment]
Yes, same with `new sys.io.Process("cat", ["/tmp/path/to/100000bytes"]);`. :face_with_thermometer:

**Comment by grepsuzette** [comment]
Gave it a try but it appears it's not the only problem.
Think for cpp I'll just use `sys.io.Process()` directly for now.
