### ISSUE TITLE
Callback when server is "actually closed"

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#17]
On nodejs, when `server.close()` is called, the server does not kill existing connections but only stop accepting new ones. When all connections have been served, the server will call the callback provided in `server.close(callback)` as well as firing a `'close'` event. I think Container should give users the ability to know such moment, because it is useful if we want to kill the process safely.

Corresponding support may be required in tink_tcp.

**Comment by back2dos** [comment]
This will be dealt with in #18.
