### ISSUE TITLE
CgiContainer constructor

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_http#2]
Any reason for the private constructor on CgiContainer?

**Comment by back2dos** [comment]
That's because it's [a singleton](https://github.com/haxetink/tink_http/blob/master/src/tink/http/Container.hx#L99), but I'm open to suggestions ;)

**Comment by benmerckx** [comment]
I missed the static `instance`, my bad :)

**Comment by back2dos** [comment]
It is quite brave of you to use the library at this time - I really appreciate that!

**Comment by benmerckx** [comment]
The hard part is the fun part :) It's also a nice opportunity to check out tink_core, it's a great toolkit.
