### ISSUE TITLE
Put error data as response body

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#21]
At [here](https://github.com/haxetink/tink_http/blob/9ebf1e2532ecc6af74ba269dd07ab89179cd7431/src/tink/http/Response.hx#L55) I would like to propose putting `haxe.Json.stringify(e.data)` instead of `e.message` because the message is already present as the reason.

**Comment by back2dos** [comment]
This is strongly related with #23. I suggest we discuss the two issues in union.
