### ISSUE TITLE
Compiling for PHP

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_http#3]
I've got some very basic routing working on neko (tcp, cgi). I'd like to compile for php but I'm running into some issues.

At compile time:
- php.Web doesn't have a logMessage method, so [this](https://github.com/haxetink/tink_http/blob/master/src/tink/http/Container.hx#L76) fails to compile. I think this could be replaced with a call to [error_log](http://php.net/manual/en/function.error-log.php).

At runtime:
- Fatal error because of the use of a `yield` method in [tink.io.Pipe](https://github.com/haxetink/tink_io/blob/master/src/tink/io/Pipe.hx#L28). This is a haxe compiler issue and I've submitted a [PR](https://github.com/HaxeFoundation/haxe/pull/4795).
- `Undefined variable: hDEFAULT (errno: 8) in ../tink/io/StdSink.class.php at line #18`: This is a weird error, as I can var_dump $hDEFAULT, php errors only if you try to call it. I think this is a compiler issue as well, I'll try to recreate this later and see why it goes wrong.

Once I messed around in the php output to circumvent the runtime issues, everything runs ok though :)

**Comment by benmerckx** [comment]
Regarding the logMessage method, ignore my suggestion of using error_log, I didn't notice this reroutes trace statements. I think anyone using the php target would expect the output of trace to be in the response. But using eg Sys.println would mess with headers that still need to be set. Maybe the best thing to do is only set haxe.Log.trace for neko, and let the user or lib decide how to handle traces?

**Comment by back2dos** [comment]
At the bottom line, I think the sanest thing to do would be to leave haxe.Log.trace completely untouched. This library has no business overwriting it. My intent was to expose neko.Web.logMessage in a convenient way, but this is over the top. I have also considered adding logging facilities right onto IncomingRequest, but that does field kind of weird. Ideas?

**Comment by benmerckx** [comment]
Leaving it untouched is probably best.
I'm not sure why you would add logging facilities onto the IncomingRequest specifically? Also where would the logs go?

**Comment by back2dos** [comment]
Well, in the case of neko.Web.logMessage it should go to the container server's log, whatever that may be. For example Apache's access log is a relatively request-centric log. I guess that's where I got the idea of putting logging right with the request ...

**Comment by benmerckx** [comment]
PR is merged: HaxeFoundation/haxe#4795 & issue is fixed, so this should compile to php with next haxe release (when the trace overwrite is removed). I do get a few showstoppers when testing with latest haxe, but those come from new compiler restrictions that apply to some tink.io modules. Will test again when there's a new release.
Regarding the logging: I can see why a log entry would be more interesting coupled with the request info. I guess nodejs/tcp can log to stdout. And for php you could then use [error_log](http://php.net/manual/en/function.error-log.php) as I don't know where else you could send it.

**Comment by back2dos** [comment]
Ok, interesting. Yes, I ran into the tink.io issues yesterday, but I didn't feel getting my hands dirty. Simn usually makes a freeze before a bigger release is made, that should give me time to either get him to make it compile again or work around it.

As for logging itself, indeed, there is always logging to stdout (or a file or whatever). A per-request log might be quite interesting, also because requests may be handled concurrently and that would really help  to tell things apart. But that's for another time. I'll just throw it out for now.

**Comment by back2dos** [comment]
Ok, I've done that now. Also I renamed `yield` to `terminate` and worked around the static lambda oddity. The latter caused a slight change in the API, but I don't think anyone relies on that just yet :)

Does that solve the problems you've been having?

**Comment by benmerckx** [comment]
Thanks, you didn't have to go through that trouble. But it is almost there now! :) 
The DEFAULT static now compiles to `static ${"DEFAULT"};` which causes a parse error in php. This probably happens because `default` itself is a reserved keyword and haxe tries to escape it, but kind of fails. I'll submit another issue on this later if I can simply reproduce it in an example.

**Comment by back2dos** [comment]
Ok, the tests for tink_io seem to indicate it works on PHP now. That should deal with the remaining issues you had.
