### ISSUE TITLE
Body handling for neko

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_http#31]
This needs to be properly solved for devtools server and for mod_neko too, somewhere around here: https://github.com/haxetink/tink_http/blob/master/src/tink/http/containers/ModnekoContainer.hx#L47

IIRC both environments deal with multipart quite differently. If someone feels able to add the mod_neko case to the current tests, that would be a great help.

**Comment by kevinresol** [comment]
FWIW, file upload simply doesn't work in ufront when running on nekotools server. Maybe because the multipart in `neko.Web` is not supported/implemented on such environment. I don't have concrete evidence though.

**Comment by benmerckx** [comment]
I can setup an apache/mod_neko docker container and setup the tests. But it'll take me a week or two because of other commitments. I can confirm nekotools server simply doesn't parse multipart requests.

There's also a curious case in php where for example PUT requests with multipart data are not parsed, [only POST requests](http://stackoverflow.com/a/9469615). I don't see a check for that yet.

**Comment by benmerckx** [comment]
For future reference here's what I used to test monsoon on mod_neko intially:
```
FROM debian:jessie

RUN echo "deb http://httpredir.debian.org/debian stretch main" >> /etc/apt/sources.list
RUN apt-get update && apt-get -t stretch install -y apache2 haxe libapache2-mod-neko && apt-get clean

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN a2enmod rewrite
RUN a2enmod neko

RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
```

**Comment by back2dos** [comment]
@benmerckx Thanks for the info!

The `PUT` case on PHP is ok for me. In that case you will just get a `Plain` body wrapped around PHP's `php://output` which I think is actually preferable.

Therefore, the nekotools server behavior is also ok for me. But on mod_neko you will currently get an empty `Plain` body. Not exactly pretty.

There's the matter of actually parsing mutlipart. I haven't look at `tink.http.Multipart` in a while, but I'm optimistic it shouldn't be to hard to get to work right, now that there are some tests in place. And then we can put some helpers in place to get a `StructuredBody` asynchronously (unless it was structured to start with).

**Comment by benmerckx** [comment]
I only see a check for the content-type in the php container, which makes me believe a put request would have an empty Parsed body, instead of Plain?

**Comment by back2dos** [comment]
Yes, you're right, thanks for catching that! Should be fixed [now](https://github.com/haxetink/tink_http/commit/f69f13dd3882582045dcbbc78136644bc547ed34).

**Comment by back2dos** [comment]
Ok, I'm going to pretend this is fine until the tests tell us otherwise.
