### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_http#33]
As @benmerckx pointed out in #32:

> The tests are becoming a huge mess :) How would you like to structure this? I think we need:
> - Platform specific code in separate files
> - More feedback on what test is running/failing (use a test framework)
> - A way to reliably kill the server even when things go wrong (I added a try catch around the handling for mod_neko for now)

I agree the tests are messy. For me it was mostly important to have something to have some results when I went forward with the recent API changes. But if there is any chance to structure this with reasonable effort, then by all means, let's do it!

The biggest issue with using test frameworks was that we need something async and that getting buddy and tink_runloop to work with one another is everything but easy. Here's the result for tink_tcp: https://github.com/haxetink/tink_tcp/blob/master/tests/RunTests.hx

**Comment by benmerckx** [comment]
Would the clients fail on buddy as well? I'm thinking we could run the servers in a separate process, same as php/neko now. It adds complexity but should work. Ideally every test could have its own handler and callback checking if the response is correct. For some (php/neko) we can use environment variables for others maybe write to stdin to instruct the process to server the right test.

**Comment by benmerckx** [comment]
Also the RunTests example of tink_tcp doesn't look like it's that hard? I'm probably missing something. If the exit call is all it takes, then we can work with that?

**Comment by back2dos** [comment]
Well, it manually does some of the things buddy automatically sets up. Which makes the logger hardcoded and generally leads to weird duplication. But we can start from there and at some point I'll find a solution for it in time: https://github.com/haxetink/tink_runloop/issues/1

**Comment by back2dos** [comment]
Having separate servers is probably inevitable, but I think it's actually a good idea. It would be a pretty decent solution to start all kinds of containers and then on every platform hit them with all available clients. The containers could just be dumb, in that they'd report back what they received (not unlike they do now), and the clients would then drive the tests.

**Comment by benmerckx** [comment]
So a single handler per server? That would make things easier. I wonder how you'd then test for example if the server correctly creates multiple cookies (which I've noticed [fails on mod_neko](https://github.com/benmerckx/monsoon/blob/master/src/monsoon/Response.hx#L129)). We need some way to instruct the handler to set certain headers (and other stuff).

**Comment by back2dos** [comment]
Interesting.

Ok, well, I suppose we could do this: 

1. You can `POST` a `Content-Type` of `application/echo` or something, where the body would determine the request you want back (you just `haxe.Serializer.run` on a `Pair<ResponseHeader, Array<Bytes>>`). 
2. For everything else, in the body you will just get a representation of what you've sent. 

That way we can check that:

1. Things the server should be able to send is actually delivered to the client (e.g. multiple cookies). We can just preconstruct responses on the client (to emulate complex server logic) and then tell the container to serve that.
2. Things the client sends all make it to the server. Try to set all kinds of weird things in the OutgoingRequest and then check what the server reports to have received against what was sent out.

There will no doubt be some trickier cases that will be hard to test with this setup. But if we get decent coverage over what this approach can test, we'll already have something rather solid, i.e. probably quite a bit more consistent than `haxe.Http` or `neko.Web`/`php.Web`.

**Comment by benmerckx** [comment]
That's in line with what I was thinking. I'm going to give it a try. I've simplified the testing in monsoon recently, not actually running any server, but simply checking if the handler returns the correct response. Mostly because I think testing the server part should be done in the tink_http tests.

**Comment by back2dos** [comment]
Yep, it's what I do in tink_web too :D 

I think it was a pretty fortunate decision to say that a handler is nothing but a function, because it makes it very easy to test in isolation.

**Comment by kevinresol** [comment]
I have bring back the tests in pure branch to an extent somewhat in par to master branch.

containers: node, php, neko-mod, node-tcp (nekotools server runs too, but it is [not very compliant](https://github.com/HaxeFoundation/haxe/issues/6245))
clients: curl, socket, node, js

So that means we can actually continue adding more tests!

**Comment by kevinresol** [comment]
Apparently I have tamed the tests for now.
