### ISSUE TITLE
Standardize HeaderValue

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#44]
There are a few formats that header values can be in. Here are what I have so far encountered:
1. Plain:
   `Host: localhost:8000`
2. Multiple values:
   `Accept-Encoding: gzip, deflate`
3. Extension:
   `Content-Type: multipart/form-data; boundary=--X`
4. Multiple extensions:
   `Content-Disposition: form-data; name="file2"; filename="a.html"`
5. Multiple values with extensions:
   `Accept-Language: en-US,en;q=0.5`

At a glance on these variations, I propose we have the HeaderValue represented as (or get parsed as) `Array<{value:String, extensions:Array<QueryStringParam>}>`. Does that look appropriate?

**Comment by kevinresol** [comment]
Sidenote:
`User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:29.0) Gecko/20100101 Firefox/29.0`
this looks like a gotcha if we simply split against `;`, not sure how to handle that.

**Comment by back2dos** [comment]
Is there anything more left to do here?

**Comment by kevinresol** [comment]
I think it is done

**Comment by kevinresol** [comment]
I am not sure if header extensions allow duplicate names. If not, we can use a map instead of array to hold them, which is easier to access. @back2dos do you know about that?

**Comment by back2dos** [comment]
I have no idea. How about `function parseWith<T>(parseExtension:Iterator<QueryStringParam>->T)` and build `parse` on top of it to produce maps, but people can easily do anything else, if they ever need to.
