### ISSUE TITLE
getallheaders not defined in php

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#46]
getallheaders  is apache extension and maybe be undefined in other environments

There is a polyfill: https://github.com/ralouphie/getallheaders

**Comment by benmerckx** [comment]
It should be supported on fcgi since 5.4, so maybe the polyfill isn't really necessary?

**Comment by kevinresol** [comment]
I am deploying on Google App Engine's PHP standard environment. And at there it is undefined 😕

**Comment by benmerckx** [comment]
Oh ok, well in that case I think a fall back to [Web.getClientHeaders](http://api.haxe.org/php/Web.html#getClientHeaders) might do the trick without introducing more code? Even though it still needs some post-processing: https://github.com/HaxeFoundation/haxe/pull/5270

**Comment by kevinresol** [comment]
I will leave this to @back2dos's decision
For now I am patching (uglily) like this:
![screen shot 2016-10-04 at 9 28 21 am](https://cloud.githubusercontent.com/assets/1103788/19065537/b1b0edba-8a46-11e6-9bf4-eb18867238a5.png)

**Comment by kevinresol** [comment]
I think I will just write some code within this lib and put some `#if haxe_ver` around it. Waiting for the std lib to update is just too time consuming.

**Comment by back2dos** [comment]
Reopened. See Ben's comments on the relevant pull request.
