### ISSUE TITLE
Compression?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#6]
How to enable compression (e.g. gzip) for the HTTP server?

**Comment by back2dos** [comment]
That's is not really in the scope of this library. In production, apps running on tink_http are meant to run behind a front-facing server, e.g. nginx, Apache, lighttpd, Varnish, HAProxy, ...,  which can take care of many aspects of http (e.g. https offloading, connection reuse, compression, flood protection, ...). Particularly on haxe/php it may badly hurt performance to put the compression into the app, as it will block workers with tasks that the container could do.

The focus of tink_http is to give you an API for HTTP that strives for an optimal sweet spot between directness and portability. There's still much left to do to that end, so I'm afraid that I will not be able to do it any time soon.

If you feel like implementing this in a cross-platform fashion, then I will be glad to integrate it, but I would warn you that this is no small task and it is probably wiser to rely on all the robust solutions that are already out there.

**Comment by kevinresol** [comment]
ok, I think that makes sense, thanks.
