### ISSUE TITLE
JavaServletContainer

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#61]
I never used JavaServlet before. But a quick glance through some docs seem to show that it work a bit similar to php. i.e. It starts a separate process/thread for each request.

**Comment by xm75** [comment]
I'd like to use tink_http on new JVM target, so something like this would be very helpful. How hard/easy would it be to adjust this old @kevinresol's pull request to the new codebase?

**Comment by kevinresol** [comment]
I think @Brave-Pi has a Undertow implementation, which should be more useful. Because with JavaServlet you will still need a frontend server.

**Comment by xm75** [comment]
I was thinking using Tomcat as a webserver (it's much more battle-tested and hardened than any alternative) and think_http as a cross-platform way to deal with http stuff.

I haven't been able to find that Undertow implementation you mentioned in @Brave-Pi repos. There's https://github.com/Brave-Pi/monsoon, but it seems that it implements custom tcp webserver on java target. That's interesting, but I'm not sure I would trust it enough to put it on public-facing website on this point.

**Comment by kevinresol** [comment]
Here it is: https://github.com/piboistudios/tink_web4jvm/blob/master/src/tink/http/containers/UndertowContainer.hx

**Comment by xm75** [comment]
Thanks, I'll take a deeper look at it.

I still think that JavaServletContainer would be very useful, as it's more generic - it works with any server which supports servlet api.

**Comment by kevinresol** [comment]
I think the code in the PR should just work, or with some minor adjustments.
But now I think it is better to add a `function toJavaSeverletHandler():(req:HttpServletRequest, res:HttpServletResponse)->Void` inside Handler to perform the conversion.

@back2dos what do you think? we can also move `toNodeHandler` into `Handler` too

**Comment by back2dos** [comment]
Sounds good ;)

**Comment by kevinresol** [comment]
@xm75 please try https://github.com/haxetink/tink_http/pull/125 :wink:

**Comment by piboistudios** [comment]
Not sure what the status of this is. It is a mess.

But maybe it'll give you an idea of how to link a JVM server with tink_http
(and then use the container for tink_web)

https://github.com/piboistudios/tink_web4jvm

**Comment by xm75** [comment]
Thank you, that was fast :)

I've installed the latest version from master with lix and I'm getting this error on compilation:
haxe_libraries/tink_io/0.8.0/github/904c48f73895b57212ad07dfaac579ee163f50a0/src/tink/io/java/JavaFileSink.hx:52: characters 38-43 : java.nio.channels.AsynchronousFileChannel has no field close

**Comment by kevinresol** [comment]
You need latest haxe due to https://github.com/HaxeFoundation/haxe/issues/9768

**Comment by xm75** [comment]
Ok, it works with nightly Haxe. :thumbsup:
