### ISSUE TITLE
StdClient onData

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_http#67]
I want to use a Client to download some larger files. Seems StdClient uses Http.onData, so as far as I can tell waits for everything to be downloaded and converted to String before piping to source. Could [`haxe.Http.customRequest`](http://api.haxe.org/haxe/Http.html#customRequest) be used to create a proper body Source?

**Comment by kevinresol** [comment]
I think somehow we need to either abandon StdClient, or provide a custom override of haxe.Http.
Because the std Http class is quite limited. For one it's `request()` method only supports GET and POST.

**Comment by kevinresol** [comment]
Actually, I think things would be much easier if we provide StdClient over the Socket class rather than the Http class.

**Comment by kevinresol** [comment]
Quick prototype: https://github.com/kevinresol/tink_http_fetch/blob/d47897c7345b79f9c92a8dba7b414561cf7dc696/src/tink/http/Fetch.hx#L124-L193

**Comment by kevinresol** [comment]
Let's say goodbye to StdClient

**Comment by back2dos** [comment]
\o/

**Comment by benmerckx** [comment]
Bye!
