### ISSUE TITLE
Some Documentation please

### ISSUE THREAD

**Issue by kobi2187** [haxetink/tink_http#72]
Hello, 
I am trying to use this library, but fail to understand some concepts.
for example, when constructing an outgoing request, I'm supposed to provide an instance of IdealSource. I don't even know what that means. moreover most http libraries have a simple api, I'm frankly surprised at what I see here.
so please provide more explanation in the documentation or provide a simpler api to use.
Thanks!

**Comment by back2dos** [comment]
If you want to have a simple API, just use `haxe.Http`. The point of this library is not to provide a simple api, but one that is consistent across a wide array of platforms, while exposing all features of HTTP, and doing so in through an interface that is asynchronous and streaming (although some implementations are in fact blocking and/or buffered). As for your concrete problem, an instance of `String` or `haxe.io.Bytes` is a valid `tink.io.IdealSource`. I will write documentation as my time permits it and requests phrased in the tone you employ certainly will not speed things up.

**Comment by kobi2187** [comment]
hi back2dos, I didn't mean to sound harsh. the tone of voice doesn't really come through in text.
I was just examining options for doing rest requests, and thought wrongly that this library is one of those. from the perspective of a simple lib for doing rest, it seemed quite complex. sorry for misunderstanding, certainly didn't mean to order you around if it sounded like that.

**Comment by kevinresol** [comment]
@kobi2187 free feel to ask questions in gitter: https://gitter.im/haxetink/public?utm_source=share-link&utm_medium=link&utm_campaign=share-link
