### ISSUE TITLE
Should clients return a `Promise<IncomingResponse>`?

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_http#77]
This is something I keep on thinking about: if HTTP fails on a network level, shouldn't the client just return a plain error, rather than creating a fake response with an error code?

The reason I went with the current API is that:

1. It's not always easy to know whether the error came from the server or the network level. But if we get rid of StdClient, this becomes easier.
2. I found it cumbersome to have two error cases to be handled. With `Promise` though `request(...).next(convertToErrors)` is a simple way to just have `Error` regardless of where it came from and `request(...).recover(IncomingResponse.reportError)` will give you exactly the same behavior as before. But the two sources of errors nicely exist on two different levels.

Anybody have thoughts on this?

**Comment by kevinresol** [comment]
I am all for it.

**Comment by kevinresol** [comment]
Well, I have actually changed it to Promise already. Shall we close this now?

**Comment by back2dos** [comment]
Cool :)
