### ISSUE TITLE
API to add header fields

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#80]
Since fields is private now, I think there should be an API for adding fields, probably cloning the header with `fields.concat(added)`

**Comment by back2dos** [comment]
Ok. I usually found myself in need of modifying the headers, which usually ends up in a comprehension:

```haxe
[for (f in header.fields) switch f.name {
  case HOST: new HeaderField(HOST, "foo.bar.baz");//rewrite host
  case REFERER: continue;//skip referrer
  case f: f;
}]
```

But yeah, if adding is a thing for you, feel free to make it easier for yourself :)

**Comment by kevinresol** [comment]
Seems like that will mess up with the type. say we have:

```haxe
public function concat(fields):Header;
```

Then for `RequestHeader` it will get downcast to `Header` :confused:

Is it intended to make `Header` immutable? Or should we just add `addField()` API.

**Comment by back2dos** [comment]
If possible I'd like to keep header immutable, yes.

Since the implementation is gonna be class specific anyway, you can just do:

```haxe
override public function concat(fields):ResponseHeader {
  return new ResponseHeader(this.method, this.url, this.version, this.fields.concat(fields));
}
```

**Comment by kevinresol** [comment]
oh I didn't know overridden method can return a child type 😮 :, let me try it then

**Comment by back2dos** [comment]
They can. When overriding methods, [argument types are contravariant and return types are covariant](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Inheritance_in_object-oriented_languages). Not all languages support that, but Haxe does :)

**Comment by kevinresol** [comment]
Today I learned :smile:
