### ISSUE TITLE
[node] "Error: Invalid character in statusMessage" with `OutgoingResponse.reportError`

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#85]
It puts `e.message` as response reason, they may fail on nodejs under some circumstances (not sure if it is utf8 or some special symbols)

Will come back with further investigation ...

**Comment by kevinresol** [comment]
ok it is due to utf8 characters:

```haxe
import tink.http.Response;
import tink.http.Header;

using tink.CoreApi;

class Main {
    static function main() {
        var container = new tink.http.containers.NodeContainer(8123);
        container.run(function(req) return Future.sync(new OutgoingResponse(
            new ResponseHeader(500, '錯誤', []),
            ''
        ))).eager();
    }
}
```

**Comment by back2dos** [comment]
I see. I suppose we should just use standard messages and put the actual message in the body. Which reminds me: how do you feel about merging your `http-status` into `tink_http`?

**Comment by kevinresol** [comment]
What about simply adding a dependency? :smile:

**Comment by back2dos** [comment]
Or that ;)

**Comment by kevinresol** [comment]
hmmm.. too bad the commit message can't close the issue unless on main branch
