### ISSUE TITLE
String should be HeaderName

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_http#89]
Latest haxe (4) gives me a weird compiler error: 
````
tink/http/Header.hx:245: characters 25-33 : String should be tink.http.HeaderName
tink/http/Header.hx:245: characters 25-33 : For function argument 'name'
````
Tried the following which still fails:
````
new HeaderField((s.substr(0, v): HeaderName), s.substr(v + 1).trim());
````
I could only get it to compile like this:
````
new HeaderField(@:privateAccess new HeaderName(s.substr(0, v)), s.substr(v + 1).trim());
````
This is most probably be a regression in haxe, but I'm leaving this here until I can reproduce in a simpler way.

**Comment by kevinresol** [comment]
I can confirm this

**Comment by kevinresol** [comment]
The strange bit is that two lines above there is `new HeaderField(s, null)` which worked. Pushed a workaround for now.

**Comment by back2dos** [comment]
This is probably "somehow" related to `HxOverrides`.

**Comment by kevinresol** [comment]
https://github.com/innogames/openfl/commit/d8e9cecf274e7463b38c4543c5f03b8dbdcc7d16

This looks alike to our problem.

**Comment by back2dos** [comment]
Anybody still has this issue?

**Comment by kevinresol** [comment]
The problem itself is mitigated by the workaround. What to do next is to report to Haxe. But I failed to reduce it.

**Comment by back2dos** [comment]
Fixed in Haxe.
