### ISSUE TITLE
Add IPC Support

### ISSUE THREAD

**Issue by gene-pavlovsky** [haxetink/tink_http#96]
It would be nice if the server would be able to listen on an IPC socket (e.g. UNIX domain socket, or a Windows named pipe).
Don't know about other platforms, but for Node.js, `server.listen()` supports it just as easy as listening on a TCP port, so implementation would be very simple, just need to be able to pass the path instead of port to `NodeContainer`.

**Comment by kevinresol** [comment]
related:
https://github.com/haxetink/tink_http/pull/25

**Comment by kevinresol** [comment]
NodeContainer now supports this. Do you have any other targets in mind that you want supported?

**Comment by back2dos** [comment]
Let's consider the matter concluded and deal with other platforms as the need arises.
